# DAY 3

# Question 1

In [3]:
import numpy as np

In [5]:
a=np.arange(2,50,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

In [14]:
l=[] 
m=[]
for i in range(0, 5): 
    ele = int(input())
    l.append(ele)
for i in range(0, 5): 
    ele = int(input())
    m.append(ele) 
arr1 = np.array(l)
arr2 = np.array(m)
arr3 = np.concatenate((arr1,arr2))
print(arr3)
arr4 = np.sort(arr3)
print(arr4)

1
2
3
4
5
1
2
3
4
5
[1 2 3 4 5 1 2 3 4 5]
[1 1 2 2 3 3 4 4 5 5]


# Question 3

In [32]:
def code():
    arr=np.random.rand(3,4)
    print(arr)
    print(arr.shape)
code()

[[0.95404663 0.55520486 0.46507563 0.1392307 ]
 [0.21099839 0.11865691 0.37500324 0.50917444]
 [0.30364584 0.90493642 0.36399515 0.38615295]]
(3, 4)


# Question 4

In [30]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
print('1D Numpy array:')
print(arr)
print('2D Numpy array:')
print(arr_2d)

1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]
2D Numpy array:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[np.newaxis])
print()
print(np.expand_dims(arr, axis = 1) )
print()
arr = np.array([[0, 1, 2],[ 3, 4, 5], [6, 7, 8]])
print(np.expand_dims(arr, axis = 2))
print()
arr = np.array([[[0, 1],[2, 3]],[[4, 5], [6, 7]]])
print(np.expand_dims(arr, axis = 3))

[[0 1 2 3 4 5 6 7 8 9]]

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]

 [[6]
  [7]
  [8]]]

[[[[0]
   [1]]

  [[2]
   [3]]]


 [[[4]
   [5]]

  [[6]
   [7]]]]


# Question 5

In [28]:
l=[]
m=[]
n=int(input("Enter the number of rows you want- "))
for i in range(0,n*n):
    ele=int(input())
    l.append(ele)
for i in range(0,n*n):
    ele=int(input())
    m.append(ele)
arr1 = np.array(l)
arr2 = np.array(m)
n=np.vstack((arr1,arr2))
print(n)
m=np.hstack((arr1,arr2))
print(m)

Enter the number of rows you want- 2
1
1
1
1
2
2
2
2
[[1 1 1 1]
 [2 2 2 2]]
[1 1 1 1 2 2 2 2]


## Question 6:

In [34]:
l = []
n = int(input("Number of elements you want to input- "))
for i in range(0, n): 
    ele = int(input())
    l.append(ele)
m = [] 
for item in l: 
    if item not in m: 
        m.append(item) 
print("Originally entered list-")
print(l)
print("Number of unique elements- "+str(len(m)))
print("Our list containing only unique elements-")
print(m)

Number of elements you want to input- 4
1
2
1
3
Originally entered list-
[1, 2, 1, 3]
Number of unique elements- 3
Our list containing only unique elements-
[1, 2, 3]
